### ISSUE TITLE
歪脖子方向支持定义旋转角度

### ISSUE THREAD

**Issue by Dina1335** [double2kill/copy-jira-commit#17]
用户可以根据自己的喜欢旋转方向~

**Comment by double2kill** [comment]
解决了，支持了两种模式。
![image](https://github.com/user-attachments/assets/30b8aaa8-70a7-42d7-bd8e-a6e060d3486c)
![image](https://github.com/user-attachments/assets/0bd232aa-2acd-4d2f-9c8a-3f58f308508c)
